import { StyleSheet } from "react-native";

export const jobPageStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f2f8f8",
  },
  header: {
    position: "relative",
    minHeight: 150,
    backgroundColor: "#2CA6A4",
    paddingTop: 38,
    paddingBottom: 22,
    paddingHorizontal: 20,
    overflow: "hidden",
    justifyContent: "center",
  },
  headerContent: {
    width: "78%",
  },
  headerCircleLarge: {
    position: "absolute",
    top: -50,
    right: -50,
    width: 180,
    height: 180,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 90,
  },
  headerCircleSmall: {
    position: "absolute",
    top: 45,
    right: 35,
    width: 85,
    height: 85,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 45,
  },
  headerSmallText: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 1.2,
    marginBottom: 5,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
    marginBottom: 6,
  },
  headerDescription: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 13,
    lineHeight: 19,
  },
  headerIcon: {
    position: "absolute",
    right: 16,
    top: 38,
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    padding: 16,
    gap: 14,
    paddingBottom: 100,
  },
  resultScoreCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e0f0ef",
    shadowColor: "#2CA6A4",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  resultScoreHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  resultScoreHeaderText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1a2e2e",
  },
  resultScoreBody: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 16,
  },
  resultCircleWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  resultCircleOuter: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 8,
    borderColor: "#2CA6A4",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e8f7f6",
  },
  resultCircleInner: {
    justifyContent: "center",
    alignItems: "center",
  },
  resultScoreValue: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1a2e2e",
  },
  resultScoreLabel: {
    fontSize: 11,
    color: "#678080",
    marginTop: 2,
  },
  resultStatusBox: {
    flex: 1,
    borderRadius: 14,
    padding: 14,
  },
  resultStatusIconRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  resultStatusTitle: {
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  resultStatusDesc: {
    fontSize: 12,
    color: "#657575",
    lineHeight: 17,
  },
  resultProgressTrack: {
    height: 6,
    borderRadius: 6,
    backgroundColor: "#e8f0f0",
    overflow: "hidden",
  },
  resultProgressFill: {
    height: "100%",
    borderRadius: 6,
  },
  resultCareerCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e0f0ef",
    shadowColor: "#2CA6A4",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  resultCareerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  resultCareerHeaderText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1a2e2e",
  },
  resultCareerDesc: {
    fontSize: 12,
    color: "#687878",
    lineHeight: 18,
    marginBottom: 14,
  },
  resultCareerItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f7fefe",
    borderWidth: 1,
    borderColor: "#d5eeec",
    borderRadius: 14,
    padding: 13,
    marginBottom: 10,
  },
  resultCareerIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#e1f5f4",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    overflow: "hidden",
  },
  resultCareerImage: {
    width: 42,
    height: 42,
  },
  resultCareerContent: {
    flex: 1,
  },
  resultCareerTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a2e2e",
    marginBottom: 3,
  },
  resultCareerText: {
    fontSize: 11,
    color: "#718181",
    lineHeight: 16,
  },
  supportCard: {
    backgroundColor: "#fff7f7",
    borderRadius: 18,
    padding: 22,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ffd6d6",
  },
  supportIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#ffe6e6",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  supportTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#b02a2a",
    marginBottom: 7,
  },
  supportDescription: {
    fontSize: 12,
    color: "#7d6060",
    textAlign: "center",
    lineHeight: 19,
  },
  restartButton: {
    borderWidth: 1,
    borderColor: "#2CA6A4",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 20,
  },
  restartButtonText: {
    color: "#2CA6A4",
    fontSize: 14,
    fontWeight: "700",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: "85%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  title: {
    flex: 1,
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2d2d",
    marginRight: 12,
  },
  image: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    marginBottom: 14,
  },
  company: {
    fontSize: 15,
    color: "#5b6b6b",
    marginBottom: 10,
  },
  tags: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  },
  tag: {
    backgroundColor: "#e6f6f5",
    color: "#2CA6A4",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    fontSize: 13,
    overflow: "hidden",
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1f2d2d",
    marginTop: 6,
    marginBottom: 4,
  },
  body: {
    fontSize: 14,
    lineHeight: 21,
    color: "#4a5a5a",
    marginBottom: 10,
  },
});